export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTR_SUCCESS = 'REGISTR_SUCCESS';
export const REGISTR_FAIL = 'REGISTR_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FETCH_TRANSACTION_STATS = "FETCH_TRANSACTION_STATS";
export const FETCH_TRANSACTION_LIST = "FETCH_TRANSACTION_LIST";
export const TRANSACTION_FAIL = "TRANSACTION_FAIL";